<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0 nav-6 category-item level-top ui-menu-item"><a href="#">Page 1</a></li>
        <li class="level0 nav-6 category-item level-top ui-menu-item"><a href="#">Page 2</a></li>
        <li class="level0 nav-6 category-item level-top ui-menu-item"><a href="#">Page 3</a></li>
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
    </ul>
    <!-- <pre>Override. From Skeleton, in: "Magento_Theme/templates/html/topmenu.phtml"</pre> -->
</nav>
